### ISSUE TITLE
Get region biasing (city) dynamically

### ISSUE THREAD

**Issue by ShivanKaul** [ShivanKaul/HashMaps#5]

**Comment by ShivanKaul** [comment]
- http://stackoverflow.com/questions/4061301/region-biasing-with-google-maps
  http://diveintohtml5.info/geolocation.html
- Currently get country code dynamically but need to center in on city dynamically as well.

**Comment by dfpoon** [comment]
This extension is useful and handy. However, it keeps redirecting me to http://www.google.ca/maps/ instead of my current country (which should be .hk). 

Could you make it redirecting to www.google.com instead? Or you may add a text field / combo box for users to specify it explicitly.

Keep up the good work!

**Comment by ShivanKaul** [comment]
Hey! Yes, I see now that I had [started working on](https://github.com/ShivanKaul/HashMaps/blob/master/extension/src/js/get-country-from-ip.js) getting current country, but I seemed to have completely forgotten about it, and hardcoded '.ca' in the main logic. I'll fix that soon, once I get time. Feel free to send a PR!

**Comment by dfpoon** [comment]
Actually '.ca' is not a problem at all, it's just a bit weird.

As mentioned in my previous response, I don't mind inputting that personally and simply using 'google.com'. You may just pick the easy way. Keep up the good work!

**Comment by ShivanKaul** [comment]
Hi @dfpoon, this problem should be solved by d5e645f939e2cb2afbb4679c67c9b0e29b9ecf07.
